### ISSUE TITLE
sonar will not start: Missing property sonar.embeddedDatabase.port

### ISSUE THREAD

**Issue by ltutar** [maestrodev/puppet-sonarqube#76]
I tried to install sonarqube through yaml with 

```
sonarqube::version: '5.6'
```

sonar will not start and gives the following error:

```
2016.07.01 10:32:55 INFO  web[o.s.p.ProcessEntryPoint] Starting web
2016.07.01 10:32:56 INFO  web[o.s.s.a.TomcatContexts] Webapp directory: /usr/local/sonarqube-5.6/web
2016.07.01 10:32:56 INFO  web[o.a.c.h.Http11NioProtocol] Initializing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.07.01 10:32:56 INFO  web[o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2016.07.01 10:32:58 INFO  web[o.s.s.p.ServerImpl] SonarQube Server / 5.6 / 074f3d1169f9688d15af4aff67e7e672cbeed782
2016.07.01 10:32:58 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.IllegalArgumentException: Missing property sonar.embeddedDatabase.port
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-17.0.jar:na]
    at org.sonar.server.db.EmbeddedDatabase.getRequiredSetting(EmbeddedDatabase.java:97) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.db.EmbeddedDatabase.startServer(EmbeddedDatabase.java:66) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.db.EmbeddedDatabase.start(EmbeddedDatabase.java:61) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.db.EmbeddedDatabaseFactory.start(EmbeddedDatabaseFactory.java:44) ~[sonar-server-5.6.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
    at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.15.jar:na]
    at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.15.jar:na]
    at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320) ~[sonar-core-5.6.jar:na]
    at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.15.jar:na]
    at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.15.jar:na]
    at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.15.jar:na]
    at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.15.jar:na]
    at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016) ~[picocontainer-2.15.jar:na]
    at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009) ~[picocontainer-2.15.jar:na]
    at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767) ~[picocontainer-2.15.jar:na]
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141) ~[sonar-core-5.6.jar:na]
    at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:84) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.platform.Platform.start(Platform.java:216) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.platform.Platform.startLevel1Container(Platform.java:175) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.platform.Platform.init(Platform.java:90) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43) ~[sonar-server-5.6.jar:na]
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.30.jar:8.0.30]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.30.jar:8.0.30]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
2016.07.01 10:32:58 ERROR web[o.a.c.c.StandardContext] One or more listeners failed to start. Full details will be found in the appropriate container log file
2016.07.01 10:32:58 ERROR web[o.a.c.c.StandardContext] Context [] startup failed due to previous errors
2016.07.01 10:32:59 INFO  web[o.a.c.h.Http11NioProtocol] Starting ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.07.01 10:32:59 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2016.07.01 10:32:59 INFO  web[o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2016.07.01 10:32:59 WARN  web[o.s.p.ProcessEntryPoint] Fail to start web
java.lang.IllegalStateException: Webapp did not start
    at org.sonar.server.app.EmbeddedTomcat.isUp(EmbeddedTomcat.java:84) ~[sonar-server-5.6.jar:na]
    at org.sonar.server.app.WebServer.isUp(WebServer.java:47) [sonar-server-5.6.jar:na]
    at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:105) ~[sonar-process-5.6.jar:na]
    at org.sonar.server.app.WebServer.main(WebServer.java:68) [sonar-server-5.6.jar:na]
2016.07.01 10:32:59 INFO  web[o.a.c.h.Http11NioProtocol] Pausing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.07.01 10:33:00 INFO  web[o.a.c.h.Http11NioProtocol] Stopping ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.07.01 10:33:00 INFO  web[o.a.c.h.Http11NioProtocol] Destroying ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.07.01 10:33:00 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2016.07.01 10:33:00 INFO  app[o.s.p.m.Monitor] Process[es] is stopping
2016.07.01 10:33:01 INFO   es[o.s.p.StopWatcher]  Stopping process
2016.07.01 10:33:01 INFO   es[o.elasticsearch.node]  [sonar-1467361959545] stopping ...
2016.07.01 10:33:01 INFO   es[o.elasticsearch.node]  [sonar-1467361959545] stopped
2016.07.01 10:33:01 INFO   es[o.elasticsearch.node]  [sonar-1467361959545] closing ...
2016.07.01 10:33:01 INFO   es[o.elasticsearch.node]  [sonar-1467361959545] closed
2016.07.01 10:33:01 INFO  app[o.s.p.m.Monitor] Process[es] is stopped
<-- Wrapper Stopped
```

**Comment by knagu** [comment]
same issue for me as well. How to rectify this?
